Repository silverstripe/cwp-installer, pull requests merged in 2018-02, with the labels that each got.

#7 Update cow configuration to include new GitHub slug and vendors
  .cow.json
Labels: affects/v4

#9 NEW Add htaccess rule to rewrite traffic to public web directory
  .htaccess
Labels: affects/v4

#10 Remove obsolete _config.php file
  mysite/_config.php
Labels: affects/v4, effort/easy, impact/low, type/enhancement

#12 Remove lekoala/silverstripe-debugbar from dev requirements
  composer.json
Labels: affects/v4

#11 Allow developers to better use _ss_environment.php
  mysite/_config.php
Labels: affects/v3, change/minor, effort/easy, impact/low, type/enhancement

#14 FIX don't try to test non existent files
  .travis.yml
Labels: affects/v4, change/patch, effort/easy, impact/low, type/bug
